# Generated by Django 4.1.2 on 2023-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncKey',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
